// ---------------------------------------------------------------------------
// Campus Security Overwatch: Formatted Printable Report Generator
// ---------------------------------------------------------------------------

export function printCsvReport(
  reportType: "visits" | "house_helps" | "incidents",
  range: string,
  csvText: string,
  printWindow: Window
) {
  const rows = csvText
    .split("\n")
    .filter((r) => r.trim())
    .map((r) => {
      const regex = /(?:,|\n|^)("(?:(?:"")*[^"]*)*"|[^",\n]*|(?:\n|$))/g;
      const matches: string[] = [];
      let match;
      while ((match = regex.exec(r)) !== null) {
        if (match.index === regex.lastIndex) regex.lastIndex++;
        if (match[1] !== undefined) {
          matches.push(match[1].replace(/^"|"$/g, "").replace(/""/g, '"'));
        }
      }
      return matches;
    });

  const headers = rows[0] || [];
  const bodyRows = rows.slice(1);

  const title =
    reportType === "visits"
      ? "Campus Gate Traffic & Check-In Log"
      : reportType === "house_helps"
      ? "Campus Domestic Staff & House Helps Directory"
      : "Campus Security Incidents & Conduct Audit";

  const tableHeadersHtml = headers.map((h) => `<th>${h}</th>`).join("");
  const tableBodyHtml = bodyRows
    .map(
      (row) => `<tr>${row.map((cell) => `<td>${cell || "—"}</td>`).join("")}</tr>`
    )
    .join("");

  const doc = printWindow.document;
  doc.open();
  doc.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - ${new Date().toLocaleDateString()}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 25px; color: #0f172a; }
          .header { border-bottom: 2px solid #0f172a; padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end; }
          .title { font-size: 18px; font-weight: 800; color: #0f172a; }
          .subtitle { font-size: 12px; color: #64748b; margin-top: 4px; font-weight: 600; }
          .meta { text-align: right; font-size: 11px; color: #475569; }
          table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 11px; }
          th { background-color: #f1f5f9; color: #334155; font-weight: 700; text-align: left; padding: 7px 8px; border: 1px solid #cbd5e1; font-size: 10px; text-transform: uppercase; }
          td { padding: 6px 8px; border: 1px solid #e2e8f0; }
          tr:nth-child(even) { background-color: #f8fafc; }
          .footer { margin-top: 25px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; }
          @media print { @page { margin: 12mm; size: landscape; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="title">🛡️ Thapar Campus Security Administration</div>
            <div class="subtitle">${title} (Scope: ${range.toUpperCase()})</div>
          </div>
          <div class="meta">
            <div><strong>Generated On:</strong> ${new Date().toLocaleString()}</div>
            <div><strong>Total Records:</strong> ${bodyRows.length}</div>
          </div>
        </div>
        <table>
          <thead><tr>${tableHeadersHtml}</tr></thead>
          <tbody>${tableBodyHtml}</tbody>
        </table>
        <div class="footer">
          Confidential Security Report • Generated by Campus Security Administration Overwatch System • Thapar Institute
        </div>
      </body>
    </html>
  `);
  doc.close();

  setTimeout(() => {
    printWindow.focus();
    printWindow.print();
  }, 250);
}
